# PIS COFINS

In [86]:
import pandas as pd

icms_path = '../resources/icms.xlsx'
piscofins_path = '../resources/piscofins.xlsx'

In [87]:
df_piscofins = pd.read_excel(piscofins_path, engine='calamine')

df_piscofins['NCM'] = df_piscofins['NCM'].str.replace('.', '', regex=False)

df_piscofins_updated = df_piscofins
df_piscofins_updated = df_piscofins_updated.drop(['Obs: Planilha exportada do ITC em 11/06/2024'], axis=1)

In [88]:

df_sieg = pd.read_excel('../resources/sieg/sieg.xlsx', sheet_name='PRODUTOS', dtype={'NCM': str}, engine='calamine')

In [89]:
# --- ETAPA DE LIMPEZA ---
# Garante que ambas as colunas NCM são do tipo string (texto)
df_sieg['NCM'] = df_sieg['NCM'].astype(str)
df_piscofins_updated['NCM'] = df_piscofins_updated['NCM'].astype(str)

# Remove espaços em branco do início e do fim das colunas
df_sieg['NCM'] = df_sieg['NCM'].str.strip()
df_piscofins_updated['NCM'] = df_piscofins_updated['NCM'].str.strip()


# --- SEU CÓDIGO ORIGINAL (AGORA MAIS SEGURO) ---

# 1. Crie o mapa de consulta (lookup map) a partir do DataFrame já limpo
piscofins_indexed = df_piscofins_updated.set_index('NCM')['TRIBUTAÇÃO']

# 2. Mapeie os valores para a coluna 'PIS COFINS'
df_sieg['PIS COFINS'] = df_sieg['NCM'].map(piscofins_indexed)
df_sieg['PIS COFINS'] = df_sieg['PIS COFINS'].fillna('NCM NÃO IDENTIFICADO')

df_sieg = df_sieg[['PIS COFINS'] + [col for col in df_sieg.columns if col != 'PIS COFINS']]
df_sieg

,PIS COFINS,CHAVE NFE,NATUREZA OPERAÇÃO,NF,DATA EMISSAO,CHAVE NFE REFER,TIPO DE OPERAÇÃO,FINALIDADE,OPERAÇÃO CONSUMIDOR FINAL,STATUS,...,BC II,VLR II,VLR DESP ADU,VLR IOF IMPORT,VLR AFRMM,NUM DI,NUM ADICAO DI,CNPJ ADQUIRENTE,UF DESEMB,DATA DESEMB
0,MONOFÁSICO,42240509373798000191550100001365561493419385,Venda de Mercadoria,136556,2024-05-02,NaN,1,1,1,100,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,MONOFÁSICO,42240509373798000191550100001365561493419385,Venda de Mercadoria,136556,2024-05-02,NaN,1,1,1,100,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,MONOFÁSICO,42240509373798000191550100001365561493419385,Venda de Mercadoria,136556,2024-05-02,NaN,1,1,1,100,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,MONOFÁSICO,42240509373798000191550100001365561493419385,Venda de Mercadoria,136556,2024-05-02,NaN,1,1,1,100,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,MONOFÁSICO,42240509373798000191550100001365571712583875,Venda de Mercadoria,136557,2024-05-02,NaN,1,1,0,100,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57644,MONOFÁSICO,42241209373798000191550110000058681000072118,VENDA DE MERCADORIA,5868,2024-12-31,NaN,1,1,1,100,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
57645,MONOFÁSICO,42241209373798000191550110000058691000072123,VENDA DE MERCADORIA,5869,2024-12-31,NaN,1,1,1,100,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
57646,MONOFÁSICO,42241209373798000191550110000058701000072132,VENDA DE MERCADORIA,5870,2024-12-31,NaN,1,1,1,100,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
57647,MONOFÁSICO,42241209373798000191550110000058711000072148,VENDA DE MERCADORIA,5871,2024-12-31,NaN,1,1,1,100,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
57648,MONOFÁSICO,42241209373798000191550110000058721000072153,VENDA DE MERCADORIA,5872,2024-12-31,NaN,1,1,1,100,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# ICMS

In [90]:
df_icms = pd.read_excel(icms_path, engine='calamine', dtype={
  'INICIO': str, 'FIM': str, 'NCM': str
})
df_icms['INICIO'] = pd.to_datetime(df_icms['INICIO'], dayfirst=True, format='mixed')
df_icms['FIM'] = pd.to_datetime(df_icms['FIM'], dayfirst=True, format='%d/%m/%Y')


df_icms['INICIO'] = df_icms['INICIO'].dt.strftime('%d/%m/%Y')
df_icms['FIM'] = df_icms['FIM'].dt.strftime('%d/%m/%Y')


df_icms

,NCM,INICIO,FIM,CEST,DESCRIÇÃO,CLASSIFICAÇÃO
0,38151210,01/01/2018,31/03/2020,01.001.00,Catalisadores em colmeia cerâmica ou metálica ...,ST
1,38151290,01/01/2018,31/03/2020,01.001.00,Catalisadores em colmeia cerâmica ou metálica ...,ST
2,39171010,01/01/2018,31/03/2020,01.002.00,"Tubos e seus acessórios (por exemplo, juntas, ...",ST
3,39171021,01/01/2018,31/03/2020,01.002.00,"Tubos e seus acessórios (por exemplo, juntas, ...",ST
4,39171029,01/01/2018,31/03/2020,01.002.00,"Tubos e seus acessórios (por exemplo, juntas, ...",ST
...,...,...,...,...,...,...
15252,97052900,01/01/1900,31/12/2050,NaN,NaN,NORMAL
15253,97053100,01/01/1900,31/12/2050,NaN,NaN,NORMAL
15254,97053900,01/01/1900,31/12/2050,NaN,NaN,NORMAL
15255,97061000,01/01/1900,31/12/2050,NaN,NaN,NORMAL
15256,97069000,01/01/1900,31/12/2050,NaN,NaN,NORMAL

In [91]:
df_sieg['DATA EMISSAO'] = pd.to_datetime(df_sieg['DATA EMISSAO'], format='%Y-%m-%d')
df_sieg['DATA EMISSAO'] = pd.to_datetime(df_sieg['DATA EMISSAO'].dt.strftime('%d/%m/%Y'), dayfirst=True)
df_sieg

,PIS COFINS,CHAVE NFE,NATUREZA OPERAÇÃO,NF,DATA EMISSAO,CHAVE NFE REFER,TIPO DE OPERAÇÃO,FINALIDADE,OPERAÇÃO CONSUMIDOR FINAL,STATUS,...,BC II,VLR II,VLR DESP ADU,VLR IOF IMPORT,VLR AFRMM,NUM DI,NUM ADICAO DI,CNPJ ADQUIRENTE,UF DESEMB,DATA DESEMB
0,MONOFÁSICO,42240509373798000191550100001365561493419385,Venda de Mercadoria,136556,2024-05-02,NaN,1,1,1,100,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,MONOFÁSICO,42240509373798000191550100001365561493419385,Venda de Mercadoria,136556,2024-05-02,NaN,1,1,1,100,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,MONOFÁSICO,42240509373798000191550100001365561493419385,Venda de Mercadoria,136556,2024-05-02,NaN,1,1,1,100,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,MONOFÁSICO,42240509373798000191550100001365561493419385,Venda de Mercadoria,136556,2024-05-02,NaN,1,1,1,100,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,MONOFÁSICO,42240509373798000191550100001365571712583875,Venda de Mercadoria,136557,2024-05-02,NaN,1,1,0,100,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57644,MONOFÁSICO,42241209373798000191550110000058681000072118,VENDA DE MERCADORIA,5868,2024-12-31,NaN,1,1,1,100,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
57645,MONOFÁSICO,42241209373798000191550110000058691000072123,VENDA DE MERCADORIA,5869,2024-12-31,NaN,1,1,1,100,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
57646,MONOFÁSICO,42241209373798000191550110000058701000072132,VENDA DE MERCADORIA,5870,2024-12-31,NaN,1,1,1,100,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
57647,MONOFÁSICO,42241209373798000191550110000058711000072148,VENDA DE MERCADORIA,5871,2024-12-31,NaN,1,1,1,100,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
57648,MONOFÁSICO,42241209373798000191550110000058721000072153,VENDA DE MERCADORIA,5872,2024-12-31,NaN,1,1,1,100,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [92]:
df_icms['INICIO'] = df_icms['INICIO'].fillna(pd.to_datetime('01/01/1990', dayfirst=True))
df_icms['FIM'] = df_icms['FIM'].fillna(pd.to_datetime('31/12/2050', dayfirst=True))

In [93]:
merged = df_sieg.merge(df_icms, on="NCM", how="left", suffixes=("", "_icms"))

# Ensure dates are datetime
merged["DATA EMISSAO"] = pd.to_datetime(merged["DATA EMISSAO"])
merged["INICIO"] = pd.to_datetime(merged["INICIO"])
merged["FIM"] = pd.to_datetime(merged["FIM"])

def classify(row):
    if pd.isna(row["INICIO"]):  
        return 'NCM não encontrado'  # No NCM found
    if row["INICIO"] <= row["DATA EMISSAO"] <= row["FIM"]:
        return row["CLASSIFICAÇÃO"]
    return "NÃO ST"

merged["ICMS"] = merged.apply(classify, axis=1)

# Keep only original SIEG columns + ICMS
final = merged[df_sieg.columns.tolist() + ["ICMS"]]

C:\TEMP\USER\ipykernel_5512\3048440680.py:6: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  merged["FIM"] = pd.to_datetime(merged["FIM"])

In [94]:
final = final[['ICMS'] + [col for col in final.columns if col != 'ICMS']]
final.to_csv('OUTPUT.CSV')

# TESTE

In [ ]:
import sqlite3


conn = sqlite3.connect('../resources/tributos.db')
cursor = conn.cursor()
cursor.execute('select * from piscofins')

# Fetch all data
data = cursor.fetchall()

# Get column names from cursor description
columns = [description[0] for description in cursor.description]

# Create DataFrame with data and column names
df = pd.DataFrame(data, columns=columns)

conn.close()

df['NCM']

KeyError: 'NCM '